### ISSUE TITLE
Font weight issue on MacOS Big Sur (11.2)

### ISSUE THREAD

**Issue by antko** [rougier/elegant-emacs#27]
Hello,

FIrst of all many thanks for sharing this setup! 
I'm on a Mac and since upgrading to MacOS Big Sur I can't use Roboto Mono Light anymore, as the informations on font weight now appear to be stripped away. As a result, when different variants of a font are installed, a single weight takes precedence over the others. In the context of `elegance.el`, only the `regular` weight of Roboto Mono is used, making the whole text to look like a long headline.
I understand that this is not an issue pertaining to `elegance.el`, but rather to emacs or Big Sur (actually I've filed a bug report here: https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00754.html) , but I was wondering whether you had a workaround in my mind? I've tried different things, but I guess my lack of lisp or emacs skills are the limiting factor here...

Many thanks in advance for your help,

Arnaud

**Comment by rougier** [comment]
I have the same problem on Big Sur and I've filled a bug but did not hear back yet (I'm using  the emacs-mac version and I think the bug is sent directly to Mitsuharu Yamamoto's.

My work around has been to split the Roboto fonts into several fonts with a unique name and a single weight. To do that I used this script: https://github.com/chrissimpkins/fontname.py. I can also send you the resulting files.

**Comment by antko** [comment]
Many thanks for this workaround!
I’ve only changed `weight: ‘light` to `:font "Roboto_Mono_Light 14”` in calls to `set-face-attribute` (where Roboto_Mono_Light is the name of the new font produced with your procedure).
I think this closes this (non-)issue.
Thanks

Arnaud
