### ISSUE TITLE
Right corner alignment off

### ISSUE THREAD

**Issue by DivineDominion** [rougier/elegant-emacs#29]
I found that, for whatever reason, the line/column indicators would crop in the corners:
https://github.com/rougier/elegant-emacs/blob/2aba642522aafc915dd6375d34602de2cf50fbec/elegant.el#L155-L171

(It's probably due to a macOS and emacs 28 font rendering issue because esp. with light fonts I ran into calculation problems in the past.)

![Screen Shot 2021-11-07 at 00 44 38](https://user-images.githubusercontent.com/59080/140627070-40f1fce7-380f-42e0-b51e-98aafa016707.png)

**Comment by DivineDominion** [comment]
To even get this, one probably needs:

    (setq frame-resize-pixelwise t)

**Comment by rougier** [comment]
The problem comes from the margin that may not be a multiple of character width and then the manual computation can only be wrong. Maybe your proposed fix might work but it depends if we can apply a specific face for between left and right parts. For the record, last time I tried, it didn't not really work.
